from agents.coding_agent import CodingAgent
from agents.testing_agent import TestingAgent
from workflows.state_manager import WorkflowStateManager


class CodingWorkflow:

    def __init__(self):
        self.coding_agent = CodingAgent()
        self.testing_agent = TestingAgent()
        self.max_retries = 1
        self.state_manager = WorkflowStateManager()

    async def run(self, user_input):

        state = self.state_manager.create_state(
            "Coding Workflow"
        )

        retry_count = 0

        #add status of current state here before getting response
        state = self.state_manager.update_step(
            state,
            "CODING",
            "Coding Agent"
        )

        coding_response = await self.coding_agent.execute(
            user_input
        )

        while retry_count <= self.max_retries:

            testing_input = f"""
            Review the following solution generated by the Coding Agent.

            Original Request:
            {user_input}

            Generated Solution:
            {coding_response}

            Check for:
            - bugs
            - scalability issues
            - security issues
            - code quality
            - improvements
            """

            state = self.state_manager.update_step(
                state,
                "TESTING",
                "Testing Agent"
            )

            testing_response = await self.testing_agent.execute(
                testing_input
            )

            if "ISSUES FOUND:" in testing_response:

                retry_count += 1

                state = self.state_manager.increment_retry(
                    state
                )

                refinement_input = f"""
                Improve the previous solution based on
                the Testing Agent feedback.

                Original Request:
                {user_input}

                Previous Solution:
                {coding_response}

                Testing Feedback:
                {testing_response}

                Generate an improved version.
                """

                #add status of current state here before getting response
                state = self.state_manager.update_step(
                    state,
                    "CODING",
                    "Coding Agent"
                )

                coding_response = await self.coding_agent.execute(
                    refinement_input
                )

            else:

                #To show completed status on dashboard (state management)
                state = self.state_manager.complete(
                    state
                )

                return {
                    "workflow": "Coding Workflow",
                    "state": state.model_dump(),
                    "status": "COMPLETED",
                    "retry_count": retry_count,
                    "final_solution": coding_response,
                    "testing_feedback": testing_response
                }

        #Incase failure in state
        state = self.state_manager.fail(
            state
        )

        return {
            "workflow": "Coding Workflow",
            "state": state.model_dump(),
            "status": "MAX RETRIES REACHED",
            "retry_count": retry_count,
            "final_solution": coding_response,
            "testing_feedback": testing_response
        }