from agents.coding_agent import CodingAgent
from agents.testing_agent import TestingAgent

def __init__(self):
    self.coding_agent = CodingAgent()
    self.testing_agent = TestingAgent()
    self.max_retries = 1

async def run(self, user_input):

    retry-count = 0

    coding_response = await self.coding_agent.execute(user_input)

    while retry_count <= self.max_retries:

            testing_input = f"""
            Review the following solution generated by the Coding Agent.

            Original Request:
            {user_input}

            Generated Solution:
            {coding_response}

            Check for:
            - bugs
            - scalability issues
            - security issues
            - code quality
            - improvements
            """

            testing_response = await self.testing_agent.execute(
                testing_input
            )

            

            if "ISSUES FOUND:" in testing_response:

                retry_count += 1

                refinement_input = f"""
                Improve the previous solution based on
                the Testing Agent feedback.

                Original Request:
                {user_input}

                Previous Solution:
                {coding_response}

                Testing Feedback:
                {testing_response}

                Generate an improved version.
                """

                coding_response = await self.coding_agent.execute(
                    refinement_input
                )

            else:

                return {
                    "workflow": "Coding Workflow",
                    "status": "COMPLETED",
                    "retry_count": retry_count,
                    "final_solution": coding_response,
                    "testing_feedback": testing_response
                }  

    return {
            "workflow": "Coding Workflow",
            "status": "MAX RETRIES REACHED",
            "retry_count": retry_count,
            "final_solution": coding_response,
            "testing_feedback": testing_response
        }